sudo: required

language: java

services: 
  - mongodb
  - rabbitmq

jdk:
  - oraclejdk8
  
before_install:
  - chmod +x pom.xml
  
script:
  - mvn -DsomeModule.test.excludes="**/FlowTest.java" test
  - mvn -DsomeModule.test.includes="**/FlowTest.java" test

